# Site
name: "FPatV"
title: "Projects and Blog"
description: "Projects and Blogs all about FPV"
meta_description: "Projects and Blogs..."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/FPatV3'
email: 'fpatv@gmx.de'
#google_analytics: 'UA-46278016-1'
disqus: 'FPatV Website'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  sal:
    name: Patrick
    display_name: FPatV
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: patv@gmx.de
    web: https://patrick131184.github.io/FPatV3/
    description: "Description of Author"
  

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
